print("Krishna")
import numpy as np
arr=np.array([[1,2,3],[1,2,3]])
print(arr)
print(type(arr))
print("The Dimesndion is : ",arr.ndim)
print("The shape is :  ",arr.shape)
print("The size is: ",arr.size)
print("The type of array: ",arr.dtype)
print()
print()
print("......NumPy Array Creation.........")
b=np.array((1,3,4))
print("Array for Tuple: ",b)
a=np.array([[1,2,4],[5,8,7]])
print("Array with List and Tuple: ",a)
c=np.zeros((3,4),dtype='int')
print("Zero Array: ",c)
d=np.full((2,3),6,dtype='complex')
print("Complex Array: \n",d)
e=np.random.random((2,3))
print("Random value of array: \n",e)
print()
print()
print(".....Reshape The Array......")
f=np.array([[1,2,4],[5,8,7]])
print("Array Is : ",f)
print("After Reshape: ",f.reshape(3,2))
print()
print()
print(".....Find Max,Min ans Sum of the Array......")
g=np.array([1,2,3,4,5,8,9,7])
print("Array is : ",g)
print("Max value in array: ",g.max())
print("Min value in array: ",g.min())
print("Sum of array: ",g.sum())
print()
print()
print(".....Arithmetic Operation on The Array......")
g=np.array([[1,3,4],[5,8,9]])
h=np.array([[1,2,4],[5,8,7]])
print("the sum of array: ",(g+h))
print("the multiplicaton of array: ",(g*h))
print("the division of array: ",(g/h))
print()
print()
print(".....Array Concatenation......")
print("Vertical Stack: \n",np.vstack((g,h)))
print("Horizontal Stack: \n",np.hstack((g,h)))
print()
print()
arr1=np.empty((3,2),dtype='int')
arr2=np.ones((2,3),dtype='int')
print("Empty array: ",arr1)
print("Ones element Array: ",arr2)
print(".........Broadcasting.........")
y=np.array([[1,2,4],[5,8,7]])
x=np.array([[1,2,4],[5,8,7],[3,2,5]])
c=y*x[:len(y)]
print(c)



