str1='Python Is Simple Lang123'
list=["java","is","lang"]
print(len(str1))               
print(type(str1(123)))
print(str1.lower())
print(str1.upper())     
print(str1.capitalize())
print(str1.title())         
print(str1.strip())
print(str1.rstrip())
print(str1.lstrip())
print(str1.replace("python","java"))
print(str1.find("p"))  
print(str1.count("p"))
print(str1.startswith("h"))
print(str1.endswith("u"))
print(str1.split())
print("   ".join(list))
print(str1.isalpha())
print(str1.isdigit())
print(str1.isalnum())
print(str1.isspace())
print(str1.swapcase())