print("Krishna")
import numpy as np
arr=np.array([[1,2,3],[1,2,3]])
print(arr)
print(type(arr))
print("The Dimesndion is : ",arr.ndim)
print("The shape is :  ",arr.shape)
print("The size is: ",arr.size)
print("The type of array: ",arr.dtype)
print()
print()
print("......NumPy Array Creation.........")
b=np.array((1,3,4))
print("Array for Tuple: ",b)
a=np.array([[1,2,4],[5,8,7]])
print("Array with List and Tuple: ",a)
c=np.zeros((3,4),dtype='int')
print("Zero Array: ",c)
d=np.full((2,3),6,dtype='complex')
print("Complex Array: \n",d)
e=np.random.random((2,3))
print("Random value of array: \n",e)
print()
print()
print(".....Reshape The Array......")
f=np.array([[1,2,4],[5,8,7]])
print("Array Is : ",f)
print("After Reshape: ",f.reshape(3,2))
print()
print()
print(".....Find Max,Min ans Sum of the Array......")
g=np.array([1,2,3,4,5,8,9,7])
print("Array is : ",g)
print("Max value in array: ",g.max())
print("Min value in array: ",g.min())
print("Sum of array: ",g.sum())
print()
print()
print(".....Arithmetic Operation on The Array......")
g=np.array([[1,3,4],[5,8,9]])
h=np.array([[1,2,4],[5,8,7]])
print("the sum of array: ",(g+h))
print("the multiplicaton of array: ",(g*h))
print("the division of array: ",(g/h))
print()
print()
print(".....Array Concatenation......")
print("Vertical Stack: \n",np.vstack((g,h)))
print("Horizontal Stack: \n",np.hstack((g,h)))
print()
print()
arr1=np.empty((3,2),dtype='int')
arr2=np.ones((2,3),dtype='int')
print("Empty array: ",arr1)
print("Ones element Array: ",arr2)
print(".........Broadcasting.........")
y=np.array([[1,2,4],[5,8,7]])
x=np.array([[1,2,4],[5,8,7],[3,2,5]])
c=y*x[:len(y)]
print(c)
print()
print()
print("To Print a random data: ")
a=np.random.rand(5,2)
print(a)
b=np.random.randint(3,size=10)
print(b)
print()
print()
print("To Print a unique data: ")
c=np.unique([1,23,5,4,6,2,1,3,4,5])
print(c)
d=np.array([[1,2,5,4,3,6],[2,3,5,6,9,8]])
print("The Array is:  ",d)
e=np.unique(d)
print("The unique array is :  ",e)
print()
print()
print("Transpose Function : ...")
a=np.array([[1,2],[2,3],[7,8]])
print("Array is :  ",a)
b=np.transpose(a)
print("The Transpose Array is: ",b)
a=np.ones((12,32,123,64))
b=np.transpose(a,(1,3,0,2)).shape
print("First Transpose: ",b)
c=np.transpose(a,(0,3,1,2)).shape
print("Second Transpose: ",c)
b=np.array((1,3,4))
print("Mean of Array: ",np.mean(b))
a=np.arange(12)
b=np.where(a<6,a,5*a)
print("Array using Where: ",b)
print()
print()
a=np.uint32([6,2])
print(a)
a_list=list(a)
a_list
a=np.array([[6,2],[31,41]])
print("Array is: ",a)
b=a.tolist()
print("After tolist: ",b)
print()
print()
a=np.dot(6,12)
print(a)




