print("..........Python Pandas...............")
print("Series")
import pandas as pd
import numpy as np
info=np.array(['p','a','n','d','a','s'])
a=pd.Series(info)
print(a)
print()
print()
print("Retrieving Dimension,Size,and number of Bytes")
a=pd.Series(data=[1,2,3,4])
b=pd.Series(data=[4,9,5,6,8,3],index=['u','v','w','x','y','z'])
print(a.ndim,b.ndim)
print(a.size,b.size)
print(a.nbytes,b.nbytes)
print()
print()
print("....DataFrames...")
df=pd.DataFrame()
print(df)
print()
a=['Pandas','Python']
df=pd.DataFrame(a)
print(df)
print()
a={'ID':[101,102,103],'Department':['B.sc','B.tech','M.Tech']}
df=pd.DataFrame(a)
print(df)
print()
a={'One':pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f']),
   'two':pd.Series([1,2,3,4],index=['a','b','c','d'])}
df=pd.DataFrame(a)
print(df)
print()
print()
print("Column Selction")
a={'One':pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f']),
   'two':pd.Series([1,2,3,4],index=['a','b','c','d'])}
d1=pd.DataFrame(a)
print(d1['One'])
print()
print()
print("Column Addition")
a={'One':pd.Series([1,2,3,4,5,6],index=['a','b','c','d','e','f']),
   'two':pd.Series([1,2,3,4],index=['a','b','c','d'])}
d1=pd.DataFrame(a)
print("Add new Column")
df['Three']=pd.Series([20,30,40,50,60],index=['a','b','c','d','e'])
df['four']=df['One']+df['Three']
print(df)
print()
print()
print("Column Deletion")
print("Delete the One column:")
del df['One']
print(df)
print("Delete the another column")
df.pop('Three')
print(df)
print()
print()
print("Appends Function")
info1=pd.DataFrame({"x":[25,15,12,19],"y":[47,24,17,29]})
info2=pd.DataFrame({"x":[25,15,12],"y":[47,24,17],"z":[38,12,45]})
print(info1._append(info2))
print()
print()
print("Apply Function")
info=pd.DataFrame([[2,7]]*4,columns=['p','q'])
print(info.apply(np.sqrt))
print()
print()
print("....Aggregate Function......")
info=pd.DataFrame([[1,5,7],[10,12,15],[18,21,24],[np.nan,np.nan,np.nan]],columns=['x','y','z'])
print(info.agg(['sum','min','max']))
print()
print()
print("....Sort Function......")
info=pd.DataFrame(index=[1,2,5,4,7,9,3,0,6,8],columns=['col4','col3'])
print(info)
info['col4']=[10,20,50,40,80,70,90,30,0,60]
info['col3']=[100,200,500,400,800,700,900,300,0,600]
info_2=info.sort_index()
print(info_2)
print()
print()
print("....Sum Function for DataFrame......")
data={'A':[1,2,3,None],
      'B':[4,None,6,7],
      'C':[None,None,None,None]
      }
df=pd.DataFrame(data)
print("Original DataFrames:")
print(df)
col_sum=df.sum()
print("\n Column_wise sum(min.count=0):")
print(col_sum)
print(df.head(2))
print()
print()
print("....Join Function......")
info=pd.DataFrame({'key':['k0','k1','k2','k3','k4','k5'],'A':['A0','A1','A2','A3','A4','A5']})
x=pd.DataFrame({'key':['k0','k1','k2'],'B':['B0','B1','B2']})
info1=info.join(x,lsuffix='_caller',rsuffix='x')
print(info1)
print()
print()
print("....Rename Function......")
info.rename(columns={'key':'Key'},inplace=True)
print(info)
print()
print()
print("....Pivot_table Function......")
table=pd.pivot_table(info,index=['Key','A'])
print(table)